name: Use Shared Workflow

on:
  push:  # This is just an example trigger, you can choose another event that suits your needs

jobs:
  trigger_shared_workflow:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger Shared Workflow
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const response = await octokit.actions.createWorkflowDispatch({
            owner: 'aabdalwahad',  # Replace with your GitHub username or organization name
            repo: 'shared-workflows',
            workflow_id: 'pr-validation.yml'  # Replace with the shared workflow filename
          });
          console.log(response);
