name: Use Shared Workflow

on:
  workflow_run:
    workflows: ["shared-workflows/pr-validation.yml"]
    types:
      - completed

jobs:
  trigger_shared_workflow:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger Shared Workflow
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const response = await octokit.actions.createWorkflowDispatch({
            owner: 'shared-workflows', // Replace with your shared repository owner
            repo: 'shared-workflows',  // Replace with your shared repository name
            workflow_id: 'pr-validation.yml'  // Replace with the shared workflow filename
          });
          console.log(response);
