name: PR Message Validation

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  validate_pr_message:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Validate PR Message
      id: validate_message
      run: |
        message=$(git log -1 --pretty=format:%s $GITHUB_SHA)
        pattern="^Issue #[0-9]+: .+"
        
        if [[ ! $message =~ $pattern ]]; then
          echo "PR message does not follow the pattern. Please use 'Issue #XXX: Your message.'"
          exit 1
        fi
        
    - name: Set Status Check
      if: ${{ failure() }}
      run: |
        echo "The PR message validation failed."
        exit 1
