name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate_pr:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Get PR Title
      run: |
        title=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" \
               | jq -r '.title')
        
        echo "PR Title: $title"
        
        title_pattern="^Issue #[0-9]+: .+"
        if [[ ! $title =~ $title_pattern ]]; then
          echo "PR title does not follow the pattern. Please use 'Issue #XXX: Your title.'"
          exit 1
        fi
        
    - name: Set Status Check
      if: ${{ failure() }}
      run: |
        echo "The PR title validation failed."
        exit 1

