name: Trigger External Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]


jobs:
  trigger_external_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger External Workflow
        env:
          REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}  # Personal access token with repo scope for the shared repository
        run: |
          title=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                 "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" \
                 | jq -r '.title')
          description=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                       "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" \
                       | jq -r '.body')
          commits=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                   "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits" \
                   | jq -r '[.[].commit.message] | join("\n")')

          pr_commits_json=$(echo "$commits" | jq -sR .)

          curl -X POST \
            -H "Authorization: token $REPO_ACCESS_TOKEN" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Content-Type: application/json" \
            "https://api.github.com/repos/aabdalwahad/shared-workflows/dispatches" \
            -d '{
              "event_type": "trigger-pr-validation",
              "client_payload": {
                "pr_number": ${{ github.event.pull_request.number }},
                "pr_title": "'"$title"'",
                "pr_description": "'"$description"'",
                "pr_commits": '"$pr_commits_json"',
                "branch": "main"
              }
            }'
