name: Trigger External Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]


jobs:
  trigger_external_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger External Workflow
        env:
          REPO_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Personal access token with repo scope for the shared repository
        run: |
          curl -X POST \
            -H "Authorization: token $REPO_ACCESS_TOKEN" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            "https://api.github.com/repos/aabdalwahad/shared-workflows/dispatches" \
            -d '{
              "event_type": "trigger-pr-validation",  # Event name defined in the shared workflow
              "client_payload": {
                "branch": "main"  # Replace with the branch you want to target in the shared workflow
              }
            }'
