name: Trigger External Workflow and Wait

on:
  workflow_run:
    workflows: ["PR Title, Description, and Commit Messages Validation"]
    types:
      - completed

jobs:
  trigger_and_wait:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger External Workflow
        env:
          REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          sha="${{ github.event.workflow_run.head_sha }}"
          title=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                 "https://api.github.com/repos/${{ github.repository }}/pulls/$sha" \
                 | jq -r '.title')
          description=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                       "https://api.github.com/repos/${{ github.repository }}/pulls/$sha" \
                       | jq -r '.body')
          commits=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                   "https://api.github.com/repos/${{ github.repository }}/pulls/$sha/commits" \
                   | jq -r '[.[].commit.message] | join("\n")')

          pr_commits_json=$(echo "$commits" | jq -sR .)

          curl -X POST \
            -H "Authorization: token $REPO_ACCESS_TOKEN" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Content-Type: application/json" \
            "https://api.github.com/repos/aabdalwahad/shared-workflows/dispatches" \
            -d '{
              "event_type": "trigger-pr-validation",
              "client_payload": {
                "pr_number": "'"$sha"'",
                "pr_title": "'"$title"'",
                "pr_description": "'"$description"'",
                "pr_commits": '"$pr_commits_json"',
                "branch": "main"
              }
            }'

      - name: Wait for Workflow Completion
        id: wait
        run: echo "Waiting for the shared workflow to complete"
        timeout-minutes: 30

      - name: Check Status
        run: |
          status=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                   "https://api.github.com/repos/aabdalwahad/shared-workflows/commits/$sha/check-suites" \
                   | jq -r '.check_suites[0].conclusion')
          echo $status
          if [[ $status == "failure" ]]; then
            echo "The shared workflow has failed. Preventing merge..."
            exit 1
          fi
